name: Deploy Hugo site to Pages

on:
  push:
    branches:
      - main  # 如果你默认分支是 master，记得改成 master

  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: true  # 这行是关键，保证拉取子模块主题！
          fetch-depth: 1

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.165.0'  # 和你本地版本保持一致

      # 👇 下面这一段是新增的“缓存”功能，能让下次构建更快
      - name: Cache Hugo resources
        uses: actions/cache@v4
        with:
          path: |
            resources
            .hugo_build.lock
          key: ${{ runner.os }}-hugo-${{ hashFiles('**/hugo.toml') }}
          restore-keys: |
            ${{ runner.os }}-hugo-

      - name: Build
        run: hugo --minify

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./public

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
